import QueryWrapper from "@/components/common/QueryWrapper";
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background">
        <QueryWrapper>{children}</QueryWrapper>
        <Toaster richColors />
      </body>
    </html>
  );
}
