import QueryWrapper from "@/components/wrapper/QueryWrapper";
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { NavHeader } from "@/components/common/Headers";
import { ContextWrapper } from "@/components/wrapper/ContextWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryWrapper>
          <ContextWrapper>
            <NavHeader />
            <main className="h-full bg-background">{children}</main>
            <Toaster richColors />
          </ContextWrapper>
        </QueryWrapper>
      </body>
    </html>
  );
}
