export const queryKeys = {
  authUser: "authUser",
  mutateTransaction: "mutateTransaction",
  mutateCategory: "mutateCategory",
  category: "category",
  categories: "categories",
  transactions: "transactions",
  deleteTransaction: "deleteTransaction",
  deleteCategory: "deleteCategory",
  emoji: "emoji",
  user: "user",
  categoryDate: "categoryDate",
  transactionFilter: "transactionFilter",
  profile: "profile",
  monthAmount: "monthAmount",
  top5CategoriesOfMonth: "top5CategoriesOfMonth",
  top5TransactionsOfMonth: "top5TransactionsOfMonth",
  transactionsThisMonth: "transactionsThisMonth",
  transactionThisWeek: "transactionThisWeek",
  transactionsToday: "transactionsToday",
  lastMonthSummary: "lastMonthSummary",
  sources: "sources",
  lastMonthCategories: "lastMonthCategories",
  proactiveInsights: "proactive-insights",
  savedConversations: "savedConversations",
};
